spring.application.name=foodhub
spring.datasource.url=jdbc:postgresql://localhost:5432/foodhub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

jwt.secret=we6tyRj61mqFSvDFbwX7HDg6wWyy7fcqtOuRpNZbANU=
jwt.expiration=3600000